# Generated by Django 5.1.1 on 2024-09-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
