# Generated by Django 5.1.1 on 2024-09-21 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donation_id_remove_donor_id_and_more'),
        ('reports', '0002_remove_cause_id_cause_cause_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='campaign_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.cause'),
        ),
    ]
