# Generated by Django 5.1.1 on 2024-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='id',
        ),
        migrations.AddField(
            model_name='cause',
            name='cause_id',
            field=models.CharField(default='DEFAULT_CAUSE_ID', max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
